<?php

namespace App\Services;

use App\Models\Certificate;
use App\Models\Course;
use App\Models\Enrollment;
use App\Models\User;
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class CertificateService
{
    public function generateCertificateNumber(): string
    {
        $prefix = 'CERT-';
        $random = strtoupper(Str::random(8));
        $number = $prefix . $random;

        while (Certificate::where('certificate_number', $number)->exists()) {
            $number = $prefix . strtoupper(Str::random(8));
        }

        return $number;
    }

    public function generate(Enrollment $enrollment, ?User $issuedBy = null, bool $autoGenerated = true): Certificate
    {
        $certificate = Certificate::create([
            'user_id' => $enrollment->user_id,
            'course_id' => $enrollment->course_id,
            'enrollment_id' => $enrollment->id,
            'certificate_number' => $this->generateCertificateNumber(),
            'issued_at' => now(),
            'is_auto_generated' => $autoGenerated,
            'issued_by' => $issuedBy?->id,
        ]);

        $this->generatePdf($certificate);

        if ($autoGenerated) {
            $enrollment->update(['completed_at' => now()]);
        }

        return $certificate;
    }

    public function generatePdf(Certificate $certificate): string
    {
        $certificate->load(['user', 'course', 'enrollment']);

        $pdf = Pdf::loadView('certificates.template', [
            'certificate' => $certificate,
        ]);

        $filename = "certificate-{$certificate->certificate_number}.pdf";
        $path = "certificates/{$filename}";

        Storage::disk('public')->put($path, $pdf->output());

        $certificate->update(['file_path' => $path]);

        return $path;
    }

    public function download(Certificate $certificate)
    {
        $certificate->load(['user', 'course']);

        if (!$certificate->file_path || !Storage::disk('public')->exists($certificate->file_path)) {
            $this->generatePdf($certificate);
        }

        return Storage::disk('public')->download(
            $certificate->file_path,
            "certificate-{$certificate->course->slug}.pdf"
        );
    }

    public function stream(Certificate $certificate)
    {
        $certificate->load(['user', 'course']);

        if (!$certificate->file_path || !Storage::disk('public')->exists($certificate->file_path)) {
            $this->generatePdf($certificate);
        }

        return Storage::disk('public')->download(
            $certificate->file_path,
            "certificate-{$certificate->course->slug}.pdf"
        );
    }
}
