<?php

namespace App\Jobs;

use App\Models\Enrollment;
use App\Services\CertificateService;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Queue\Queueable;

class GenerateCertificate implements ShouldQueue
{
    use Queueable;

    public function __construct(
        public Enrollment $enrollment,
        public bool $autoGenerated = true
    ) {}

    public function handle(CertificateService $certificateService): void
    {
        $certificateService->generate($this->enrollment, null, $this->autoGenerated);
    }
}
